version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
    - 7.21.0
  - dependency-name: swr
    versions:
    - 0.3.11
    - 0.4.1
    - 0.4.2
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: eslint-config-prettier
    versions:
    - 7.1.0
    - 7.2.0
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: styled-components
    versions:
    - 5.2.1
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 11.0.0
